### PR TITLE
Add color parameter

### LINKED ISSUE #20: Allow passing a color to default
In some circumstances it is nice to be able to bypass the palette and choose a specific color for the avatar directly. We should allow a `color` parameter that will override the default.

### PR DESCRIPTION
**Pull request by ClemMakesApps**
Example:
screen shot 2016-10-03 at 11 41 35 am

Closes #20 🎃

### CODE REVIEW

**Comment by tommoor** [comment]
I think it would be clearer to have the '#' character included in the parameter rather than appended automatically. I really need to get some validation on these parameters but I think that's a problem for another PR!

**Comment by ClemMakesApps** [comment]
Hmm, I originally wanted to include the `#` but it wasn't getting passed into the params. I need to do some digging but it might not be feasible depending on how express has implemented their route params parsing

**Comment by tommoor** [comment]
Hmm, I can see why the pound sign would be a problem actually - it might need to be encoded, but then that's not terribly clear either so...

*thinks*

**Comment by tommoor** [comment]
_2 years passes_

I went with those approach, but added validation so that we're not passing user provided values directly into ImageMagick 😉  83a151467808f4c9f0dfa1b1b9b49b2b7c3d794d

**Pull request closed without merging**
